[package]
name = "html"
version = "0.1.0"
edition = "2024"

[dependencies]
memchr = "2"
tools = { path = "../tools" }

[features]
count-alloc = []
html5-entities = []
perf-tests = []
internal-api = []
dom-snapshot = []
