[package]
name = "runtime_net"
version = "0.1.0"
edition = "2024"

[dependencies]
app_api = { path = "../app_api" }
bus = { path = "../bus" }
net = { path = "../net" }
html = { path = "../html", features = ["internal-api"] }
core_types = { path = "../core_types" }
